name: deno

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup latest deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: run deno fmt
        run: deno fmt --check

      - name: run deno lint
        run: deno lint --unstable

  tests:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Setup latest deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: run deno test
        run: deno test -A --unstable
