name: deno

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup latest deno version
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: run deno fmt
        run: deno fmt --check

      - name: run deno lint
        run: deno lint --unstable
